#!/usr/bin/env python3
"""
Load parsed Mass propers (Advent, Christmas, Lent, Ordinary Time) into lit_part_sources.

Reads JSON files generated by parse_propers.py:
    translations/advent_propers.json
    translations/christmas_propers.json
    translations/lent_propers.json
    translations/ordinary_propers.json

Usage:
    python translations/load_propers.py [--dry-run]
    --dry-run  Print rows to be inserted without touching the database.
"""

import json
import sys
import argparse
from pathlib import Path

HERE = Path(__file__).parent


# ── DB connection ─────────────────────────────────────────────────────────

def get_engine(user='jcost', db_name='liturgio'):
    import keyring
    from sqlalchemy import create_engine, text

    password = keyring.get_password('liturgio-mysql', user)
    if password is None:
        sys.exit(f'ERROR: No keyring password for {user}@{db_name}.')
    conn_str = f'mysql+mysqlconnector://{user}:{password}@localhost:3306/{db_name}'
    engine = create_engine(conn_str, future=True)
    with engine.connect() as conn:
        conn.execute(text('SELECT 1'))
    return engine


# ── Row builder ───────────────────────────────────────────────────────────

# cycle_sun: Year A=1, Year B=2, Year C=0 (per CLAUDE.md)
YEAR_CYCLE = {'Year A': 1, 'Year B': 2, 'Year C': 0}

SERVICE_PARTS = {
    'entrance_antiphon': 'in',
    'communion_antiphon': 'co',
}


def _epoch_slug(season, subseason, wknum, seq):
    """
    Compute the lit_epoch slug from seasonal key columns.
    Matches the slug patterns in lit_epoch (see make-lit-epoch.sql):
      day:       {season}-{subseason}-{wknum:02d}-{seq}
      week:      {season}-{subseason}-{wknum:02d}
      subseason: {season}-{subseason}
      season:    {season}
    Returns None if season is absent.
    """
    if not season:
        return None
    if not subseason:
        return season
    if seq is not None and wknum is not None:
        return f"{season}-{subseason}-{wknum:02d}-{seq}"
    if wknum and wknum > 0:
        return f"{season}-{subseason}-{wknum:02d}"
    return f"{season}-{subseason}"


def build_rows(entry):
    """
    Expand one JSON day entry into a list of row dicts for lit_part_sources.
    Skips antiphons with no Latin text.
    Multiple antiphon alternatives become separate rows.
    """
    season   = entry['season']
    subseason = entry.get('subseason')
    wknum    = entry.get('wknum')
    rows = []
    for field, part_code in SERVICE_PARTS.items():
        for antiphon in entry.get(field, []):
            latin = antiphon.get('latin', '').strip()
            if not latin:
                continue
            year_label = antiphon.get('year')
            seq = entry.get('wkday')
            rows.append({
                'lit_epoch_slug':            _epoch_slug(season, subseason, wknum, seq),
                'wkday':                     seq,
                'cycle_sun':                 YEAR_CYCLE.get(year_label) if year_label else None,
                'cycle_wkday':               None,
                'service_part':              part_code,
                'original_text':             latin,
                'vernacular_text':           antiphon.get('english') or None,
                'text_src':                  antiphon.get('citation') or None,
                'original_lang':             'la',
                'vernacular_lang':           'en',
                'assignment_authority_code': 'MISSAL',
                'translation_source_code':   'ROMAN_MISSAL_2010_ICEL',
            })
    return rows


# ── Main ─────────────────────────────────────────────────────────────────

JSON_FILES = [
    HERE / 'advent_propers.json',
    HERE / 'christmas_propers.json',
    HERE / 'lent_propers.json',
    HERE / 'ordinary_propers.json',
]

INSERT_SQL = """
    INSERT INTO lit_part_sources
        (lit_epoch_slug, wkday, cycle_sun, cycle_wkday,
         service_part, original_text, vernacular_text, text_src,
         original_lang, vernacular_lang,
         assignment_authority_code, translation_source_code)
    VALUES
        (:lit_epoch_slug, :wkday, :cycle_sun, :cycle_wkday,
         :service_part, :original_text, :vernacular_text, :text_src,
         :original_lang, :vernacular_lang,
         :assignment_authority_code, :translation_source_code)
"""


def main():
    sys.stdout.reconfigure(encoding='utf-8')
    parser = argparse.ArgumentParser()
    parser.add_argument('--dry-run', action='store_true',
                        help='Print rows without inserting into the database')
    args = parser.parse_args()

    all_rows = []
    for json_path in JSON_FILES:
        if not json_path.exists():
            print(f'WARNING: {json_path.name} not found, skipping.')
            continue
        with open(json_path, encoding='utf-8') as f:
            days = json.load(f)
        file_rows = []
        skipped = 0
        for entry in days:
            rows = build_rows(entry)
            if rows:
                file_rows.extend(rows)
            else:
                skipped += 1
        print(f'{json_path.name}: {len(days)} entries -> {len(file_rows)} rows ({skipped} entries skipped, no antiphons)')
        all_rows.extend(file_rows)

    print(f'\nTotal rows to insert: {len(all_rows)}')

    if args.dry_run:
        print('\n--- DRY RUN: first 5 rows ---')
        for r in all_rows[:5]:
            print(' ', r)
        return

    engine = get_engine('jcost')
    from sqlalchemy import text
    with engine.begin() as conn:
        conn.execute(text(INSERT_SQL), all_rows)
        count = conn.execute(text('SELECT COUNT(*) FROM lit_part_sources')).scalar()
        print(f'Inserted {len(all_rows)} rows. Total in lit_part_sources: {count}')

        # Quick verification
        sample = conn.execute(text(
            "SELECT lit_epoch_slug, service_part, text_src "
            "FROM lit_part_sources "
            "WHERE lit_epoch_slug NOT LIKE 'PASC%' "
            "ORDER BY lit_epoch_slug, service_part LIMIT 10"
        )).fetchall()
        print('\nSample non-Easter rows:')
        for r in sample:
            print(' ', dict(r._mapping))


if __name__ == '__main__':
    main()
